spring:
  rabbitmq:
    addresses: 47.106.10.211:5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  datasource:
    url: jdbc:mysql://localhost:3306/rabbit?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8001
  servlet:
    context-path: /
mybatis:
  type-aliases-package: com.imooc.springbootproducer
  mapper-locations: classpath:com/imooc/springbootproducer/mapping/*.xml
logging:
  level:
    tk:
      mybatis: trace
